/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from '../../prisma/prisma.service';
import { Prisma, Portfolio, Language, User } from '@prisma/client';
import { PortfolioCreateInput } from './PortfolioCreateInput';
import { Portfolio as PortfolioNow } from './Portfolio';
import { UserWhereUniqueInput } from 'src/user/base/UserWhereUniqueInput';
import { UserInfo } from 'src/auth/UserInfo';

export class PortfolioServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PortfolioCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.PortfolioCountArgs>
  ): Promise<number> {
    return this.prisma.portfolio.count(args);
  }

  async findMany<T extends Prisma.PortfolioFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PortfolioFindManyArgs>
  ): Promise<Portfolio[]> {
    return this.prisma.portfolio.findMany(args);
  }
  async findOne<T extends Prisma.PortfolioFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PortfolioFindUniqueArgs>
  ): Promise<Portfolio | null> {
    return this.prisma.portfolio.findUnique(args);
  }
  async create<T extends Prisma.PortfolioCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PortfolioCreateArgs>
  ): Promise<Portfolio> {
    return this.prisma.portfolio.create<T>(args);
  }
  async update<T extends Prisma.PortfolioUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PortfolioUpdateArgs>
  ): Promise<Portfolio> {
    return this.prisma.portfolio.update<T>(args);
  }
  async delete<T extends Prisma.PortfolioDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PortfolioDeleteArgs>
  ): Promise<Portfolio> {
    return this.prisma.portfolio.delete(args);
  }

  async findLanguage(
    parentId: string,
    args: Prisma.LanguageFindManyArgs
  ): Promise<Language[]> {
    return this.prisma.portfolio
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .language(args);
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.portfolio
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }

  async createPorfolio(data: PortfolioCreateInput, userId: string) {
    const portfolio = this.prisma.portfolio.create({
      data: {
        ...data,
        user: {
          connect: {
            id: userId,
          },
        },
      },
      select: {
        category: true,
        createdAt: true,
        githubUrl: true,
        id: true,
        image: true,
        info: true,
        liveUrl: true,
        updatedAt: true,
        userId: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });

    return portfolio;
  }
}
