/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreatePortfolioArgs } from "./CreatePortfolioArgs";
import { UpdatePortfolioArgs } from "./UpdatePortfolioArgs";
import { DeletePortfolioArgs } from "./DeletePortfolioArgs";
import { PortfolioCountArgs } from "./PortfolioCountArgs";
import { PortfolioFindManyArgs } from "./PortfolioFindManyArgs";
import { PortfolioFindUniqueArgs } from "./PortfolioFindUniqueArgs";
import { Portfolio } from "./Portfolio";
import { LanguageFindManyArgs } from "../../language/base/LanguageFindManyArgs";
import { Language } from "../../language/base/Language";
import { User } from "../../user/base/User";
import { PortfolioService } from "../portfolio.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Portfolio)
export class PortfolioResolverBase {
  constructor(
    protected readonly service: PortfolioService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Portfolio",
    action: "read",
    possession: "any",
  })
  async _portfoliosMeta(
    @graphql.Args() args: PortfolioCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Portfolio])
  @nestAccessControl.UseRoles({
    resource: "Portfolio",
    action: "read",
    possession: "any",
  })
  async portfolios(
    @graphql.Args() args: PortfolioFindManyArgs
  ): Promise<Portfolio[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Portfolio, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Portfolio",
    action: "read",
    possession: "own",
  })
  async portfolio(
    @graphql.Args() args: PortfolioFindUniqueArgs
  ): Promise<Portfolio | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Portfolio)
  @nestAccessControl.UseRoles({
    resource: "Portfolio",
    action: "create",
    possession: "any",
  })
  async createPortfolio(
    @graphql.Args() args: CreatePortfolioArgs
  ): Promise<Portfolio> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Portfolio)
  @nestAccessControl.UseRoles({
    resource: "Portfolio",
    action: "update",
    possession: "any",
  })
  async updatePortfolio(
    @graphql.Args() args: UpdatePortfolioArgs
  ): Promise<Portfolio | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Portfolio)
  @nestAccessControl.UseRoles({
    resource: "Portfolio",
    action: "delete",
    possession: "any",
  })
  async deletePortfolio(
    @graphql.Args() args: DeletePortfolioArgs
  ): Promise<Portfolio | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Language], { name: "language" })
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "read",
    possession: "any",
  })
  async resolveFieldLanguage(
    @graphql.Parent() parent: Portfolio,
    @graphql.Args() args: LanguageFindManyArgs
  ): Promise<Language[]> {
    const results = await this.service.findLanguage(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldUser(
    @graphql.Parent() parent: Portfolio
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
